<div class="row">
<div class="col-md-3"></div>
<div class="col-md-6">
<div class="panel panel-default">
<div class="panel-heading">
    <h3 class="panel-title">Настройка IP-адреса сервера</h3>
</div>
    <table class="table table-bordered table-hover">
        <tbody>
        <tr>
            <td>Server IP</td>
            <td><input type="text" class="form-control"></td>
        </tr>
        <tr>
            <td>Port</td>
            <td><input type="text" class="form-control"></td>
        </tr>
        <tr>
            <td>Интервал опроса состояния сети</td>
            <td><input type="text" class="form-control"></td>
        </tr>
        <tr>
            <td>Интервал опроса соглосования данных</td>
            <td><input type="text" class="form-control"></td>
        </tr>
        <tr>
            <td>Максимальное допустимое отклонение</td>
            <td><input type="text" class="form-control"></td>
        </tr>
        <tr>
            <td>Путь к Лире</td>
            <td><input type="text" class="form-control"></td>
        </tr>
        <tr>
            <td>Локальная папка</td>
            <td><input type="text" class="form-control"></td>
        </tr>
        <tr>
            <td>Уведомления</td>
            <td>
                <div class="checkbox col-sm-2">
                    <label>
                        <input type="checkbox"> активировать
                    </label>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
    <div class="panel-body">
    <button type="button" class="btn btn-default">Ok</button>
    <button type="button" class="btn btn-default">Отменить</button>
</div>
</div>
</div>
<div class="col-md-3"></div>
</div>
