<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Диплом')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.file-input.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="container">
            <div style="position:fixed;top:10px;right:10px;">
                <a title="Домой" href="/">
                    <span class="glyphicon glyphicon-home"></span>
                </a>
                <a title="Настройки" href="/application/config/index" style="margin-left: 5px">
                    <span class="glyphicon glyphicon-cog"></span>
                </a>
                <?php if(isset($this->user) && $this->user instanceof \Application\Entity\User): ?>
                    <a title="Выход" href="/application/user/logout" style="margin-left: 5px">
                        <span class="glyphicon glyphicon-log-out"></span>
                    </a>
                <?php endif; ?>
            </div>
            <?php if(isset($_SESSION) && array_key_exists('flush_error', $_SESSION)): ?>
                <div class="alert alert-danger alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <?php echo $_SESSION['flush_error'] ?>
                </div>
                <?php unset($_SESSION['flush_error']); ?>
            <?php endif; ?>
            <?php echo $this->content; ?>
            <hr>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
