<div class="row">
<div class="col-md-12">
<div class="panel panel-default">
<div class="panel-heading">
    <h3 class="panel-title">Таблица</h3>
</div>
<div class="panel-body">
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th></th>
            <th>№ сечения</th>
            <th>ПЕ</th>
            <th>-</th>
            <th>ПЕ</th>
            <th>№ общ. узла</th>
            <th>X, м</th>
            <th>Y, м</th>
            <th>Z, м</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>1</td>
            <td>1</td>
            <td>1</td>
            <td>-</td>
            <td>2</td>
            <td>1</td>
            <td>-5.000</td>
            <td>2.0</td>
            <td>0</td>
        </tr>
        <tr>
            <td>2</td>
            <td>1</td>
            <td>1</td>
            <td>-</td>
            <td>2</td>
            <td>2</td>
            <td>2</td>
            <td>3</td>
            <td>3</td>
        </tr>
        <tr>
            <td>3</td>
            <td>2</td>
            <td>2</td>
            <td>-</td>
            <td>3</td>
            <td>1</td>
            <td>-3.123</td>
            <td>2</td>
            <td>3</td>
        </tr>
        <tr>
            <td>4</td>
            <td>3</td>
            <td>3</td>
            <td>-</td>
            <td>4</td>
            <td>1</td>
            <td>1</td>
            <td>2</td>
            <td>2</td>
        </tr>
        <tr>
            <td>5</td>
            <td>3</td>
            <td>3</td>
            <td>-</td>
            <td>4</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
        </tr>
        <tr>
            <td>6</td>
            <td>3</td>
            <td>3</td>
            <td>-</td>
            <td>4</td>
            <td>3</td>
            <td>-4</td>
            <td>5.54</td>
            <td>6</td>
        </tr>
        </tbody>
    </table>
    <button type="button" class="btn btn-default">Согласовать данные</button>
    <button type="button" class="btn btn-danger">х</button>
</div>
</div>
</div>
</div>
