<div class="row">
<div class="col-md-3"></div>
<div class="col-md-6">
<div class="panel panel-default">
<div class="panel-heading">
    <h3 class="panel-title">Состояние ПЕ (Обновлено - 17.02.2014 21:51)</h3>
</div>
<div class="panel-body">
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>РЕ</th>
            <th>ФИО Проектировщика</th>
            <th>БПС</th>
            <th>Этап</th>
            <th>Дата-Время</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>1</td>
            <td>Иванов</td>
            <td>Лира9</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>2</td>
            <td>Петров</td>
            <td>Лира9</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>3</td>
            <td>Сидоров</td>
            <td>Лира9</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>4</td>
            <td>Егоров</td>
            <td>Лира9</td>
            <td></td>
            <td></td>
        </tr>
        </tbody>
    </table>
    <button type="button" class="btn btn-default">Назад</button>
    <button type="button" class="btn btn-success">Обновить</button>
</div>
</div>
</div>
<div class="col-md-3"></div>
</div>
